spring:
  application:
    name: turbin
  rabbitmq:
    host: 176.212.33.20
    port: 5672
    username: admin
    password: admin  
    
server:
  port: 5001
  
eureka:
  client:
    service-url:
      defaultZone: http://eureka1:2001/eureka, http://eureka2:2002/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}:PY
      
turbine:
  app-config: order-service, zuul
  cluster-name-expression: new String("default")
#集群名字 new String("default")
#监控的服务名 order-service, zuul
