spring:
  application:
    name: zuul
  rabbitmq:
    host: 176.212.33.20
    port: 5672
    username: admin
    password: admin
  sleuth:
    sampler:
      probability: 0.1    
    
server:
  port: 3001
  
eureka:
  client:
    service-url:
      defaultZone: http://eureka1:2001/eureka, http://eureka2:2002/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}:PY
#zuul:
#  routes:
#    item-service: /item-service/**
#    user-service: /user-service/**
#    order-service: /order-service/**
    
zuul:
  retryable: true 
  
ribbon:
  ConnectTimeout: 1000
  ReadTimeout: 1000
  MaxAutoRetriesNextServer: 1
  MaxAutoRetries: 1  
  
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 50000  
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream  
